快適な環境
1
自分の好きにやらせてくれる環境
ポジションや役割が明確な環境
瞬間的な判断力やかけひき強さが活かせる環境
ゆっくり時間をかけて結果を出すことが求められる環境
常に新鮮さがあり、カッコいいと感じられる環
マイペースで取り組むことが許される環境
自分の好きにやらせてくれる環境
ポジションや役割が明確な環境
瞬間的な判断力やかけひき強さが活かせる環境
ゆっくり時間をかけて結果を出すことが求められる環境
自然体で、安心できる環境
他人からの指図が少ない環境
自分のやり方を認めてもらえる環境
目立たないが、場やチームの中心にいられる環境
瞬間的な判断力やかけひき強さが活かせる環境
ゆっくり時間をかけて結果を出すことが求められる環境
自然体で、安心できる環境
他人からの指図が少ない環境
自分のやり方を認めてもらえる環境
目立たないが、場やチームの中心にいられる環境
束縛されない環境
束縛されない環境
目立たないが、場やチームの中心にいられる環境
自分のやり方を認めてもらえる環境
自分のやり方を認めてもらえる環境
目立たないが、場やチームの中心にいられる環境
束縛されない環境
束縛されない環境
目立たないが、場やチームの中心にいられる環境
自分のやり方を認めてもらえる環境
他人からの指図が少ない環境
自然体で、安心できる環境
ゆっくり時間をかけて結果を出すことが求められる環境
瞬間的な判断力やかけひき強さが活かせる環境
目立たないが、場やチームの中心にいられる環境
自分のやり方を認めてもらえる環境
他人からの指図が少ない環境
自然体で、安心できる環境
ゆっくり時間をかけて結果を出すことが求められる環境
瞬間的な判断力やかけひき強さが活かせる環境
ポジションや役割が明確な環境
自分の好きにやらせてくれる環境
マイペースで取り組むことが許される環境
常に新鮮さがあり、カッコいいと感じられる環
ゆっくり時間をかけて結果を出すことが求められる環境
瞬間的な判断力やかけひき強さが活かせる環境
ポジションや役割が明確な環境
自分の好きにやらせてくれる環境
マイペースで取り組むことが許される環境
常に新鮮さがあり、カッコいいと感じられる環
序列や上下関係ががはっきりしている環境
序列や上下関係ががはっきりしている環境
常に新鮮さがあり、カッコいいと感じられる環
マイペースで取り組むことが許される環境
マイペースで取り組むことが許される環境
常に新鮮さがあり、カッコいいと感じられる環
序列や上下関係ががはっきりしている環境
序列や上下関係ががはっきりしている環境
常に新鮮さがあり、カッコいいと感じられる環
マイペースで取り組むことが許される環境

2
スピード感があり、常に好奇心を刺激される環境
実績や経験が評価される環境
堅苦しくない雰囲気
勝ち目のある勝負に挑める環境
オープンで隠し事のない環境
信頼関係がある、平和な環境
スピード感があり、常に好奇心を刺激される環境
実績や経験が評価される環境
堅苦しくない雰囲気
勝ち目のある勝負に挑める環境
無機質、人工的ではなく、自然を感じられる環境
アクシデントやトラブルをサポートしてもらえる環境
人の役に立っていることが実感できる環境
上下関係が明確な環境
堅苦しくない雰囲気
勝ち目のある勝負に挑める環境
無機質、人工的ではなく、自然を感じられる環境
アクシデントやトラブルをサポートしてもらえる環境
人の役に立っていることが実感できる環境
上下関係が明確な環境
未来に希望が持てる環境
未来に希望が持てる環境
上下関係が明確な環境
人の役に立っていることが実感できる環境
人の役に立っていることが実感できる環境
上下関係が明確な環境
未来に希望が持てる環境
未来に希望が持てる環境
上下関係が明確な環境
人の役に立っていることが実感できる環境
アクシデントやトラブルをサポートしてもらえる環境
無機質、人工的ではなく、自然を感じられる環境
勝ち目のある勝負に挑める環境
堅苦しくない雰囲気
上下関係が明確な環境
人の役に立っていることが実感できる環境
アクシデントやトラブルをサポートしてもらえる環境
無機質、人工的ではなく、自然を感じられる環境
勝ち目のある勝負に挑める環境
堅苦しくない雰囲気
実績や経験が評価される環境
スピード感があり、常に好奇心を刺激される環境
信頼関係がある、平和な環境
オープンで隠し事のない環境
勝ち目のある勝負に挑める環境
堅苦しくない雰囲気
実績や経験が評価される環境
スピード感があり、常に好奇心を刺激される環境
信頼関係がある、平和な環境
オープンで隠し事のない環境
いい加減さや間違いが少ない環境
いい加減さや間違いが少ない環境
オープンで隠し事のない環境
信頼関係がある、平和な環境
信頼関係がある、平和な環境
オープンで隠し事のない環境
いい加減さや間違いが少ない環境
いい加減さや間違いが少ない環境
オープンで隠し事のない環境
信頼関係がある、平和な環境

3
ファミリー的な温かさがある環境
他人ではなく自分しかできないなど、存在意義が感じられる環境
小さな結果でもすぐに実感できる環境
リスクが高い環境ではなく、堅実な環境
自分も含めてみんなで一緒に向上できる環境
肩書きや立場で態度をコロコロ変えなくても良い環境
ファミリー的な温かさがある環境
他人ではなく自分しかできないなど、存在意義が感じられる環境
小さな結果でもすぐに実感できる環境
リスクが高い環境ではなく、堅実な環境
心を許せる仲間と力を合わせられる環境
スピーディーな環境
人まねではなく、自分の創意工夫が発揮できる環境
相談し合えて、仲間意識の強い環境
小さな結果でもすぐに実感できる環境
リスクが高い環境ではなく、堅実な環境
心を許せる仲間と力を合わせられる環境
スピーディーな環境
人まねではなく、自分の創意工夫が発揮できる環境
相談し合えて、仲間意識の強い環境
自分のやりたいことや得意なことに没頭できる環境
自分のやりたいことや得意なことに没頭できる環境
相談し合えて、仲間意識の強い環境
人まねではなく、自分の創意工夫が発揮できる環境
人まねではなく、自分の創意工夫が発揮できる環境
相談し合えて、仲間意識の強い環境
自分のやりたいことや得意なことに没頭できる環境
自分のやりたいことや得意なことに没頭できる環境
相談し合えて、仲間意識の強い環境
人まねではなく、自分の創意工夫が発揮できる環境
スピーディーな環境
心を許せる仲間と力を合わせられる環境
リスクが高い環境ではなく、堅実な環境
小さな結果でもすぐに実感できる環境
相談し合えて、仲間意識の強い環境
人まねではなく、自分の創意工夫が発揮できる環境
スピーディーな環境
心を許せる仲間と力を合わせられる環境
リスクが高い環境ではなく、堅実な環境
小さな結果でもすぐに実感できる環境
他人ではなく自分しかできないなど、存在意義が感じられる環境
ファミリー的な温かさがある環境
肩書きや立場で態度をコロコロ変えなくても良い環境
自分も含めてみんなで一緒に向上できる環境
リスクが高い環境ではなく、堅実な環境
小さな結果でもすぐに実感できる環境
他人ではなく自分しかできないなど、存在意義が感じられる環境
ファミリー的な温かさがある環境
肩書きや立場で態度をコロコロ変えなくても良い環境
自分も含めてみんなで一緒に向上できる環境
自分も人も、完璧を追い求められるような環境
自分も人も、完璧を追い求められるような環境
自分も含めてみんなで一緒に向上できる環境
肩書きや立場で態度をコロコロ変えなくても良い環境
肩書きや立場で態度をコロコロ変えなくても良い環境
自分も含めてみんなで一緒に向上できる環境
自分も人も、完璧を追い求められるような環境
自分も人も、完璧を追い求められるような環境
自分も含めてみんなで一緒に向上できる環境
肩書きや立場で態度をコロコロ変えなくても良い環境

4
失敗しても怒られない環境
一流の物や人に触れる機会が多い環境
自分の頑張りが、合理的に評価される環境
ストレスがたまり続けない環境
新しい人やモノに頻繁に出会える環境
研究や学術など、じっくり納得して没頭できる環境
失敗しても怒られない環境
一流の物や人に触れる機会が多い環境
自分の頑張りが、合理的に評価される環境
ストレスがたまり続けない環境
焦らせたり、急かされたりしない環境
プロ意識の高い集団
行動を焦らされない環境
ズルい人や感情的にブレやすい人が少ない環境
自分の頑張りが、合理的に評価される環境
ストレスがたまり続けない環境
焦らせたり、急かされたりしない環境
プロ意識の高い集団
行動を焦らされない環境
ズルい人や感情的にブレやすい人が少ない環境
変化があり柔軟に活動できる環境
変化があり柔軟に活動できる環境
ズルい人や感情的にブレやすい人が少ない環境
行動を焦らされない環境
行動を焦らされない環境
ズルい人や感情的にブレやすい人が少ない環境
変化があり柔軟に活動できる環境
変化があり柔軟に活動できる環境
ズルい人や感情的にブレやすい人が少ない環境
行動を焦らされない環境
プロ意識の高い集団
焦らせたり、急かされたりしない環境
ストレスがたまり続けない環境
自分の頑張りが、合理的に評価される環境
ズルい人や感情的にブレやすい人が少ない環境
行動を焦らされない環境
プロ意識の高い集団
焦らせたり、急かされたりしない環境
ストレスがたまり続けない環境
自分の頑張りが、合理的に評価される環境
一流の物や人に触れる機会が多い環境
失敗しても怒られない環境
研究や学術など、じっくり納得して没頭できる環境
新しい人やモノに頻繁に出会える環境
ストレスがたまり続けない環境
自分の頑張りが、合理的に評価される環境
一流の物や人に触れる機会が多い環境
失敗しても怒られない環境
研究や学術など、じっくり納得して没頭できる環境
新しい人やモノに頻繁に出会える環境
仲間の面倒見てあげられる環境
仲間の面倒見てあげられる環境
新しい人やモノに頻繁に出会える環境
研究や学術など、じっくり納得して没頭できる環境
研究や学術など、じっくり納得して没頭できる環境
新しい人やモノに頻繁に出会える環境
仲間の面倒見てあげられる環境
仲間の面倒見てあげられる環境
新しい人やモノに頻繁に出会える環境
研究や学術など、じっくり納得して没頭できる環境
